services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/app
    tty: true
    stdin_open: true
    ports:
      - "3000:3000"

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
    tty: true
    stdin_open: true
    ports:
      - "5173:5173"